"""
matchup_data.py — Local matchup tips cache loader for RuneSync.

Reads from matchups.json which is pre-generated by the Claude generation project.
Format expected:
{
  "Darius": {
    "top": {
      "Garen": {
        "difficulty": "medium",
        "who_wins_early": "Darius",
        "trading_pattern": "...",
        "ability_to_dodge": "...",
        "power_spikes": { "you": "...", "enemy": "..." },
        "early_game": "...",
        "mid_game": "...",
        "late_game": "...",
        "win_condition": "...",
        "counter_items": ["Plated Steelcaps"],
        "scaling": "...",
        "jungle_gankable": true,
        "positioning": "..."
      }
    }
  }
}
"""

import json, os, sys, difflib
from typing import Optional

# When compiled by PyInstaller (--onefile), __file__ resolves to the temp
# extraction dir, not the exe's directory. Use sys.executable's dir instead.
if getattr(sys, "frozen", False):
    _BASE = os.path.dirname(sys.executable)
else:
    _BASE = os.path.dirname(os.path.abspath(__file__))
_CACHE_PATH = os.path.join(_BASE, "matchups.json")
_cache: Optional[dict] = None


def _load() -> dict:
    global _cache
    if _cache is not None:
        return _cache
    if not os.path.exists(_CACHE_PATH):
        _cache = {}
        return _cache
    try:
        with open(_CACHE_PATH, "r", encoding="utf-8") as f:
            _cache = json.load(f)
    except Exception:
        _cache = {}
    return _cache


def _fuzzy_key(name: str, keys: list[str]) -> Optional[str]:
    """Case-insensitive exact match first, then fuzzy fallback."""
    name_lower = name.lower()
    for k in keys:
        if k.lower() == name_lower:
            return k
    matches = difflib.get_close_matches(name, keys, n=1, cutoff=0.75)
    return matches[0] if matches else None


def get_matchup_tips(my_champ: str, enemy_champ: str, role: str = "auto") -> Optional[dict]:
    """
    Look up pre-generated matchup tips for my_champ vs enemy_champ.
    Returns the matchup dict or None if not found.
    role: "top", "mid", "jungle", "bot", "support", or "auto"
    """
    data = _load()
    if not data:
        return None

    # Find my champ entry (fuzzy)
    my_key = _fuzzy_key(my_champ, list(data.keys()))
    if not my_key:
        return None

    champ_entry = data[my_key]

    # Resolve role — try exact role first, then fall back to any role that has this matchup
    roles_to_try = []
    if role and role != "auto":
        roles_to_try.append(role)
    roles_to_try += [r for r in champ_entry.keys() if r != role]

    for r in roles_to_try:
        role_entry = champ_entry.get(r, {})
        if not role_entry:
            continue
        enemy_key = _fuzzy_key(enemy_champ, list(role_entry.keys()))
        if enemy_key:
            return role_entry[enemy_key]

    return None


def refresh_cache() -> None:
    """Force-reload matchups.json from disk, discarding the in-memory cache."""
    global _cache
    _cache = None
    _load()


def is_cache_loaded() -> bool:
    """Returns True if matchups.json exists and has data."""
    data = _load()
    return bool(data)


def cache_stats() -> dict:
    """Returns basic stats about the loaded cache for logging."""
    data = _load()
    if not data:
        return {"champions": 0, "matchups": 0}
    total_matchups = sum(
        len(matchups)
        for champ in data.values()
        for matchups in champ.values()
    )
    return {"champions": len(data), "matchups": total_matchups}
